### PR TITLE
Fix disable button overlap

### PR DESCRIPTION
**Pull request by luisbosch**
- Disable Awareness button only appears on hover of the presence div.

### CODE REVIEW

**Comment by manzato** [comment]
didn't deploy the code (don't recall how to do it). I'll try to do so tonight unless someone beats me to it.

**Comment by luisbosch** [comment]
Me neither, I recall @adamantivm saying he copied the code directly without minifcation to gh-pages.

**Comment by adamantivm** [comment]
I need to look up my references. I think it needs to be built and then copied into a gh-pages branch.
Anyone tested this?
Thanks for the contribution @luisbosch !

**Comment by manzato** [comment]
I'll test prior to deploying

**Comment by adamantivm** [comment]
?
You mean you will deploy? Or that I should wait until you test and then I deploy?

**Comment by manzato** [comment]
I'll test and deploy later today or if you can please do both things.

**Comment by manzato** [comment]
works great @luisbosch , thanks. Deployed.

**Pull request merged**
