### PR TITLE
Rebasing master to latest webogram

### PR DESCRIPTION
**Pull request by garyservin**
Created on behalf of @luisbosch

### CODE REVIEW

**Comment by adamantivm** [comment]
can't merge, it has conflicts  :-/

**Comment by luisbosch** [comment]
conflicts? Where?!?!?! :P

Fixed! @adamantivm

**Comment by adamantivm** [comment]
I can merge this but at this point I have no idea what I'm doing. Can someone else only for the sake of sanity checking (I trust you @luisbosch ) take a quick look to make sure we won't be immedia-less right after this? Maybe @manzato or @basicNew

**Comment by adamantivm** [comment]
Especially, @luisbosch , are you sure master is the right target branch?

**Comment by luisbosch** [comment]
@adamantivm I'm all in for some testing.

I've sure master is the branch. It hast the latest changes.
I've done local testing and immedia is working on my laptop with the rebase v0.6.0

image

But I'm not sure how gh-pages work... so we can always revert? :P

**Comment by adamantivm** [comment]
I found the notes that explain how it works, will send shortly.

**Pull request merged**
